Format markdown, YAML and TOML files with Prettier

diff --git a/.github/workflows/main-ci.yaml b/.github/workflows/main-ci.yaml
--- a/.github/workflows/main-ci.yaml
+++ b/.github/workflows/main-ci.yaml
@@ -23,28 +23,27 @@ on:
   push:
     # Every branch
     branches:
-      - "**"
+      - '**'
     # But do not run this workflow on creating a new tag starting with 'v', e.g. 'v1.0.3' (see pypi-publish.yml)
     tags-ignore:
       - 'v*'
   # Trigger the workflow on pull request
   pull_request:
     branches:
-      - "**"
+      - '**'
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
 # Allow only one concurrent workflow, skipping runs queued between the run in-progress and latest queued.
 # And cancel in-progress runs.
 concurrency:
-  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
+  group:
+    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
 jobs:
-
   # Job 1: Check code consistency
   code-consistency:
-
     strategy:
       matrix:
         os: [ubuntu-latest]
@@ -56,7 +55,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
-          fetch-depth: '0'  # full history with tags to get the version number by versioningit
+          fetch-depth: '0' # full history with tags to get the version number by versioningit
 
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
@@ -89,8 +88,8 @@ jobs:
       - name: Suggestion to fix linter issues (for *.ipynb files)
         if: ${{ failure() }}
         run: |
-            echo "In project root run 'nbqa ruff examples/ --fix' and commit changes to fix issues."
-            exit 1
+          echo "In project root run 'nbqa ruff examples/ --fix' and commit changes to fix issues."
+          exit 1
 
       # Install code formatter for markdown, YAML, TOML files and run in the project root
       - name: Install prettier and run in the project root
@@ -101,12 +100,12 @@ jobs:
       - name: Suggestion to fix prettier issues (for *.md, *.yaml, *.toml files)
         if: ${{ failure() }}
         run: |
-            echo "In project root run 'npx prettier . --write --config=prettierrc.toml' and commit changes to fix issues."
-            exit 1
+          echo "In project root run 'npx prettier . --write --config=prettierrc.toml' and commit changes to fix issues."
+          exit 1
 
   # Job 2: Test code and upload coverage to Codecov. Test Jupyter notebooks.
   test-code-and-notebooks:
-    needs: code-consistency  # previous job 'code-consistency' need to be finished first
+    needs: code-consistency # previous job 'code-consistency' need to be finished first
 
     # current job matrix. if modified, remember to UPDATE the strategy in the next job
     strategy:
@@ -118,79 +117,74 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: '0'  # full history with tags to get the version number by versioningit
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: '0' # full history with tags to get the version number by versioningit
 
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Upgrade package installer for Python
-      run: python -m pip install --upgrade pip
+      - name: Upgrade package installer for Python
+        run: python -m pip install --upgrade pip
 
-    - name: Install Python dependencies
-      run: pip install '.[dev,charts]'
+      - name: Install Python dependencies
+        run: pip install '.[dev,charts]'
 
-    - name: Run Python tests and create coverage report
-      run: >
-        pytest tests/
-        --cov=./
-        --cov-report=xml:coverage/coverage.xml
-        --junitxml=./coverage/junit.xml
-        --color=yes
-        -n auto
+      - name: Run Python tests and create coverage report
+        run: >
+          pytest tests/ --cov=./ --cov-report=xml:coverage/coverage.xml
+          --junitxml=./coverage/junit.xml --color=yes -n auto
 
-    #- name: Upload test results to Codecov
-    #  if: ${{ !cancelled() }}
-    #  uses: codecov/test-results-action@v1
-    #  with:
-    #    files: ./coverage/junit.xml
-    #    fail_ci_if_error: true  # optional (default = false)
-    #    name: Pytest results
-    #    token: ${{ secrets.CODECOV_TOKEN }}
+      #- name: Upload test results to Codecov
+      #  if: ${{ !cancelled() }}
+      #  uses: codecov/test-results-action@v1
+      #  with:
+      #    files: ./coverage/junit.xml
+      #    fail_ci_if_error: true  # optional (default = false)
+      #    name: Pytest results
+      #    token: ${{ secrets.CODECOV_TOKEN }}
 
-    #- name: Upload coverage report to Codecov
-    #  uses: codecov/codecov-action@v4
-    #  with:
-    #    files: ./coverage/coverage.xml
-    #    env_vars: OS,PYTHON
-    #    fail_ci_if_error: true  # optional (default = false)
-    #    name: Pytest coverage
-    #    token: ${{ secrets.CODECOV_TOKEN }}
-    #  env:
-    #    OS: ${{ matrix.os }}
-    #    PYTHON: ${{ matrix.python-version }}
+      #- name: Upload coverage report to Codecov
+      #  uses: codecov/codecov-action@v4
+      #  with:
+      #    files: ./coverage/coverage.xml
+      #    env_vars: OS,PYTHON
+      #    fail_ci_if_error: true  # optional (default = false)
+      #    name: Pytest coverage
+      #    token: ${{ secrets.CODECOV_TOKEN }}
+      #  env:
+      #    OS: ${{ matrix.os }}
+      #    PYTHON: ${{ matrix.python-version }}
 
-    - name: Run Jupyter Notebooks as tests
-      shell: bash
-      run: >
-        pytest 
-        --nbmake examples 
-        --ignore-glob='examples/*emcee*'
-        --nbmake-timeout=300 
-        --color=yes
-        -n=auto
+      - name: Run Jupyter Notebooks as tests
+        shell: bash
+        run: >
+          pytest  --nbmake examples  --ignore-glob='examples/*emcee*'
+          --nbmake-timeout=300  --color=yes -n=auto
 
-    - name: Create Python package  # dist/*.whl
-      run: python -m build --wheel --outdir dist
+      - name: Create Python package # dist/*.whl
+        run: python -m build --wheel --outdir dist
 
-    - name: Upload zipped Python package (with tests and examples) for next job
-      uses: actions/upload-artifact@v4
-      with:
-        name: EasyDiffractionLib_py${{ matrix.python-version }}_${{ matrix.os }}_${{ runner.arch }}
-        path: |
-          dist/*.whl
-          tests/
-          examples/
-        if-no-files-found: "error"
-        compression-level: 0
+      - name:
+          Upload zipped Python package (with tests and examples) for next job
+        uses: actions/upload-artifact@v4
+        with:
+          name:
+            EasyDiffractionLib_py${{ matrix.python-version }}_${{ matrix.os
+            }}_${{ runner.arch }}
+          path: |
+            dist/*.whl
+            tests/
+            examples/
+          if-no-files-found: 'error'
+          compression-level: 0
 
   # Job 3: Test the package
   test-package:
-    needs: test-code-and-notebooks  # the previous job needs to be finished first
+    needs: test-code-and-notebooks # the previous job needs to be finished first
 
     strategy:
       fail-fast: false
@@ -201,39 +195,37 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
 
-    - name: Upgrade package installer for Python
-      run: python -m pip install --upgrade pip
+      - name: Upgrade package installer for Python
+        run: python -m pip install --upgrade pip
 
-    - name: Download zipped Python package (with tests and examples) from previous job
-      uses: actions/download-artifact@v4
-      with:  # name or path are taken from the upload step of the previous job
-        name: EasyDiffractionLib_py${{ matrix.python-version }}_${{ matrix.os }}_${{ runner.arch }}
-        path: .  # directory to extract downloaded zipped artifacts
+      - name:
+          Download zipped Python package (with tests and examples) from previous
+          job
+        uses: actions/download-artifact@v4
+        with: # name or path are taken from the upload step of the previous job
+          name:
+            EasyDiffractionLib_py${{ matrix.python-version }}_${{ matrix.os
+            }}_${{ runner.arch }}
+          path: . # directory to extract downloaded zipped artifacts
 
-    # The local version must be higher than the PyPI version for pip to
-    # prefer the local version. So, after a new release and a new tag,
-    # remember to merge the master branch with the develop branch,
-    # and then create a new feature branch from the develop branch.
-    - name: Install Python package from previous job with 'dev' extras
-      run: pip install 'easydiffraction[dev]' --find-links=dist
+      # The local version must be higher than the PyPI version for pip to
+      # prefer the local version. So, after a new release and a new tag,
+      # remember to merge the master branch with the develop branch,
+      # and then create a new feature branch from the develop branch.
+      - name: Install Python package from previous job with 'dev' extras
+        run: pip install 'easydiffraction[dev]' --find-links=dist
 
-    - name: Run Python tests
-      run: >
-        pytest tests/
-        --color=yes
-        -n auto
+      - name: Run Python tests
+        run: >
+          pytest tests/ --color=yes -n auto
 
-    - name: Run Jupyter Notebooks as tests
-      shell: bash
-      run: >
-        pytest 
-        --nbmake examples/
-        --ignore-glob='examples/*emcee*'
-        --nbmake-timeout=300 
-        --color=yes
-        -n=auto  
+      - name: Run Jupyter Notebooks as tests
+        shell: bash
+        run: >
+          pytest  --nbmake examples/ --ignore-glob='examples/*emcee*'
+          --nbmake-timeout=300  --color=yes -n=auto
