disable ruff for time being

diff --git a/.github/workflows/python-ci.yml b/.github/workflows/python-ci.yml
--- a/.github/workflows/python-ci.yml
+++ b/.github/workflows/python-ci.yml
@@ -5,16 +5,16 @@ on: [push, pull_request]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  Code_Consistency:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - uses: chartboost/ruff-action@v1
-      - name: Suggestion to fix issues
-        if: ${{ failure() }}
-        run: |
-            echo "::notice::In project root run 'python.exe -m ruff . --fix' and commit changes to fix issues."
-            exit 1
+  # Code_Consistency:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - uses: chartboost/ruff-action@v1
+  #     - name: Suggestion to fix issues
+  #       if: ${{ failure() }}
+  #       run: |
+  #           echo "::notice::In project root run 'python.exe -m ruff . --fix' and commit changes to fix issues."
+  #           exit 1
 
   Code_Build:
 
